### PR TITLE
Added login to sidebar

### PR DESCRIPTION
**Pull request by junukwon7**
Added login to sidebar.
Works fine in my server.
line 204 "Don't have an account?" ==> "Dont have an account?"

### CODE REVIEW

**Comment by undefined-moe** [comment]
that's a mistake() `check in` here does not mean `sign in` (we have pop up sign in form) it is something like daily checkin which give user some credit(?) I'm not sure how to translate it properly. just like those on luogu.com.cn

**Comment by junukwon7** [comment]
> that's a mistake() `check in` here does not mean `sign in` (we have pop up sign in form) it is something like daily checkin which give user some credit(?) I'm not sure how to translate it properly. just like those on luogu.com.cn

Oh I got it. :D

**Comment by undefined-moe** [comment]
sorry for this ambiguity 😭

**Comment by junukwon7** [comment]
> sorry for this ambiguity 😭

No problem. 😄 (I just pasted it from login.html)

**Pull request closed without merging**
